/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>
/* Header for class InputFile */

#ifndef _Included_InputFile
#define _Included_InputFile
struct Hjava_lang_String;

typedef struct ClassInputFile {
    struct Hjava_lang_String *path;
#define InputFile_separatorChar 58L
    long fd;
} ClassInputFile;
HandleTo(InputFile);

extern /*boolean*/ long InputFile_open(struct HInputFile *);
extern void InputFile_close(struct HInputFile *);
extern long InputFile_read(struct HInputFile *,HArrayOfByte *,long);
#endif
