/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>
/* Header for class OutputFile */

#ifndef _Included_OutputFile
#define _Included_OutputFile
struct Hjava_lang_String;

typedef struct ClassOutputFile {
    struct Hjava_lang_String *path;
#define OutputFile_separatorChar 58L
    long fd;
} ClassOutputFile;
HandleTo(OutputFile);

extern /*boolean*/ long OutputFile_open(struct HOutputFile *);
extern void OutputFile_close(struct HOutputFile *);
extern long OutputFile_write(struct HOutputFile *,HArrayOfByte *,long);
#endif
