/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>
/* Header for class File */

#ifndef _Included_File
#define _Included_File
struct Hjava_lang_String;

typedef struct ClassFile {
    struct Hjava_lang_String *path;
#define File_separatorChar 58L
} ClassFile;
HandleTo(File);

#endif
