/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class OutputFile */
/* SYMBOL: "OutputFile/open()Z", Java_OutputFile_open_stub */
stack_item *Java_OutputFile_open_stub(stack_item *_P_,struct execenv *_EE_) {
	extern long OutputFile_open(void *);
	_P_[0].i = (OutputFile_open(_P_[0].p) ? TRUE : FALSE);
	return _P_ + 1;
}
/* SYMBOL: "OutputFile/close()V", Java_OutputFile_close_stub */
stack_item *Java_OutputFile_close_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void OutputFile_close(void *);
	(void) OutputFile_close(_P_[0].p);
	return _P_;
}
/* SYMBOL: "OutputFile/write([BI)I", Java_OutputFile_write_stub */
stack_item *Java_OutputFile_write_stub(stack_item *_P_,struct execenv *_EE_) {
	extern long OutputFile_write(void *,void *,long);
	_P_[0].i = OutputFile_write(_P_[0].p,((_P_[1].p)),((_P_[2].i)));
	return _P_ + 1;
}
