/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>
/* Header for class java_lang_String */

#ifndef _Included_java_lang_String
#define _Included_java_lang_String

typedef struct Classjava_lang_String {
    struct HArrayOfChar *value;
    long offset;
    long count;
/* Inaccessible static: InternSet */
} Classjava_lang_String;
HandleTo(java_lang_String);

#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
