/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>
/* Header for class java_lang_ClassLoader */

#ifndef _Included_java_lang_ClassLoader
#define _Included_java_lang_ClassLoader

typedef struct Classjava_lang_ClassLoader {
    char PAD;	/* ANSI C requires structures to have a least one member */
} Classjava_lang_ClassLoader;
HandleTo(java_lang_ClassLoader);

#ifdef __cplusplus
extern "C" {
#endif
struct Hjava_lang_Class;
__declspec(dllexport) struct Hjava_lang_Class *java_lang_ClassLoader_defineClass(struct Hjava_lang_ClassLoader *,HArrayOfByte *,long,long);
__declspec(dllexport) void java_lang_ClassLoader_resolveClass(struct Hjava_lang_ClassLoader *,struct Hjava_lang_Class *);
struct Hjava_lang_String;
__declspec(dllexport) struct Hjava_lang_Class *java_lang_ClassLoader_findSystemClass(struct Hjava_lang_ClassLoader *,struct Hjava_lang_String *);
__declspec(dllexport) void java_lang_ClassLoader_init(struct Hjava_lang_ClassLoader *);
#ifdef __cplusplus
}
#endif
#endif
