/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>
/* Header for class java_lang_Thread */

#ifndef _Included_java_lang_Thread
#define _Included_java_lang_Thread
struct Hjava_lang_Thread;
struct Hjava_lang_Runnable;
struct Hjava_lang_ThreadGroup;

typedef struct Classjava_lang_Thread {
    struct HArrayOfChar *name;
    long priority;
    struct Hjava_lang_Thread *threadQ;
    long PrivateInfo;
    long eetop;
    /*boolean*/ long single_step;
    /*boolean*/ long daemon;
    /*boolean*/ long stillborn;
    struct Hjava_lang_Runnable *target;
/* Inaccessible static: activeThreadQ */
    struct Hjava_lang_ThreadGroup *group;
/* Inaccessible static: threadInitNumber */
#define java_lang_Thread_MIN_PRIORITY 1L
#define java_lang_Thread_NORM_PRIORITY 5L
#define java_lang_Thread_MAX_PRIORITY 10L
} Classjava_lang_Thread;
HandleTo(java_lang_Thread);

#ifdef __cplusplus
extern "C" {
#endif
__declspec(dllexport) struct Hjava_lang_Thread *java_lang_Thread_currentThread(struct Hjava_lang_Thread *);
__declspec(dllexport) void java_lang_Thread_yield(struct Hjava_lang_Thread *);
__declspec(dllexport) void java_lang_Thread_sleep(struct Hjava_lang_Thread *,int64_t);
__declspec(dllexport) void java_lang_Thread_start(struct Hjava_lang_Thread *);
__declspec(dllexport) /*boolean*/ long java_lang_Thread_isAlive(struct Hjava_lang_Thread *);
__declspec(dllexport) long java_lang_Thread_countStackFrames(struct Hjava_lang_Thread *);
__declspec(dllexport) void java_lang_Thread_setPriority0(struct Hjava_lang_Thread *,long);
struct Hjava_lang_Object;
__declspec(dllexport) void java_lang_Thread_stop0(struct Hjava_lang_Thread *,struct Hjava_lang_Object *);
__declspec(dllexport) void java_lang_Thread_suspend0(struct Hjava_lang_Thread *);
__declspec(dllexport) void java_lang_Thread_resume0(struct Hjava_lang_Thread *);
#ifdef __cplusplus
}
#endif
#endif
